logging:
  level:
    org.springframework.security: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG # 整合了sleuth后日志输出

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}:${eureka.instance.hostname}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://192.168.10.58:8000/eureka/


security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8001/user/current
      id: smartpark-uac
    client:
      clientId: smartpark-provider-server
      grantType: client_credentials
      scope: server
      user-authorization-uri: http://localhost:8001/oauth/authorize
      clientSecret: admin
      access-token-uri: http://localhost:8001/oauth/token

# 日志收集配置
#spring:
#  rabbitmq:
#    host: rabbitmq
#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      percentage: 1.0 # 指定需要采样请求的拜访比，默认是0.1，即10%

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
